### ISSUE TITLE
Integration stopped working in 2026.8.0

### ISSUE THREAD

**Issue by a94marbo** [EHylands/ha-qolsys-panel#107]
### Checklist

- [x] I have enabled debug logging for my installation.

### Version of the panel

IQ 4 Hub

### Describe the issue

Integration fails to load after updrading to 2026.8.0.

### Debug logs

```text
Loggare: homeassistant.setup
Källa: setup.py:341
Inträffade först: 21:14:31 (1 förekomst)
Senast loggat: 21:14:31

Setup failed for custom integration 'qolsys_panel': Unable to import component: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/qolsys_panel/__init__.py", line 9, in <module>
    from qolsys_controller import qolsys_controller
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/__init__.py", line 1, in <module>
    from .controller import QolsysController as qolsys_controller  # noqa: D104, F401, N813
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/controller.py", line 21, in <module>
    from qolsys_controller.pairing_server import QolsysPairingServer
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/pairing_server.py", line 13, in <module>
    from .pki import QolsysPKI
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/pki.py", line 9, in <module>
    import aiofiles.os
  File "/usr/local/lib/python3.14/site-packages/aiofiles/os.py", line 5, in <module>
    from . import ospath as path
  File "/usr/local/lib/python3.14/site-packages/aiofiles/ospath.py", line 5, in <module>
    from .base import wrap
ImportError: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1051, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1043, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/qolsys_panel/__init__.py", line 9, in <module>
    from qolsys_controller import qolsys_controller
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/__init__.py", line 1, in <module>
    from .controller import QolsysController as qolsys_controller  # noqa: D104, F401, N813
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/controller.py", line 21, in <module>
    from qolsys_controller.pairing_server import QolsysPairingServer
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/pairing_server.py", line 13, in <module>
    from .pki import QolsysPKI
  File "/usr/local/lib/python3.14/site-packages/qolsys_controller/pki.py", line 9, in <module>
    import aiofiles.os
  File "/usr/local/lib/python3.14/site-packages/aiofiles/os.py", line 5, in <module>
    from . import ospath as path
  File "/usr/local/lib/python3.14/site-packages/aiofiles/ospath.py", line 5, in <module>
    from .base import wrap
ImportError: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)
```

**Comment by jpreiditsch** [comment]
Also seeing the same issue with the same stack trace upon first startup. Restarting Home Assistant seems to have resolved it for me.

**Comment by a94marbo** [comment]
Yes, I can confirm. A full reboot, fixes the issue.

**Comment by EHylands** [comment]
aiofiles is set a latest available version in requirement file.
Can't fully explain why, but once in a while, there seams to be a miss match between ha-qolsys panel version and qolsys-controller version when updating.
